M48
; DRILL file KiCad 10.0.6 date 2026-09-10T10:46:44
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-10T10:46:44+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,8,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.400
%
G90
G05
T1
X84.61Y-141.895
X90.39Y-141.895
X109.61Y-141.895
X115.39Y-141.895
T2
X102.8Y-116.1
X102.8Y-122.9
T3
X83.0Y-73.0
X83.0Y-132.0
X100.0Y-144.0
X117.0Y-57.0
M30
